#!/usr/bin/env bash
# =============================================================================
# Quick Mall — automated test runner (workitem #13)
# =============================================================================
# Launches Factorio headless via the FactorioTest CLI, runs the in-game specs
# (tests/qm-blueprint-tests.lua), and writes a Markdown report. Runnable by hand,
# and invoked every 6 hours by a Claude Code scheduled job (see
# .claude/scheduled_tasks.json — NOT the system crontab). Exits non-zero if any
# test fails so the scheduler / CI surface failures.
#
# The CLI is fetched on demand via `npx` (package: factorio-test-cli) so nothing
# is installed globally. Requires: node/npm (nvm), a Factorio binary (path in
# factorio-test.json), and network access on first run to fetch the CLI.
#
# Report: docs/test-results/latest.md (overwritten each run); the raw run is also
# echoed to stdout for the scheduler log.
#
# Undo: this whole workitem reverts via
#   git revert $(git log --grep="workitem-13" -1 --format=%H)
# and the schedule is removed by deleting the "Quick Mall automated test run" job
# from .claude/scheduled_tasks.json (or via the CronDelete tool in Claude Code).
# =============================================================================
set -uo pipefail

# Resolve repo root (this script lives in <repo>/scripts/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}" || exit 1

# Make nvm-installed node/npx reachable from a bare scheduler environment.
# Discover the newest nvm node bin dir under $HOME rather than pinning a version
# or a username-specific absolute path.
NVM_NODE_BIN="$(ls -d "${HOME}"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1)"
export PATH="${NVM_NODE_BIN:+${NVM_NODE_BIN}:}/opt/homebrew/bin:${PATH}"

RESULTS_DIR="${REPO_ROOT}/docs/test-results"
REPORT="${RESULTS_DIR}/latest.md"
mkdir -p "${RESULTS_DIR}"

# --- macOS Steam-bundle data-path workaround -------------------------------
# On the macOS Steam build the binary lives at factorio.app/Contents/MacOS/
# factorio but its `core`/`base` data are at factorio.app/Contents/data. The
# default config.ini the CLI writes uses read-data=__PATH__executable__/../../
# data, which the binary resolves to factorio.app/data (nonexistent) and aborts
# with "There is no package core". We pre-seed the data dir's config.ini with an
# ABSOLUTE read-data pointing at .../Contents/data. The CLI leaves an existing
# config.ini's read-data untouched (it only rewrites write-data), so this sticks.
FACTORIO_BIN="${HOME}/Library/Application Support/Steam/steamapps/common/Factorio/factorio.app/Contents/MacOS/factorio"
DATA_DIR="${REPO_ROOT}/factorio-test-data-dir"
if [ -x "${FACTORIO_BIN}" ]; then
  # .../factorio.app/Contents/MacOS/factorio -> .../factorio.app/Contents/data
  READ_DATA="$(cd "$(dirname "${FACTORIO_BIN}")/.." && pwd)/data"
  if [ -d "${READ_DATA}" ] && [ ! -f "${DATA_DIR}/config.ini" ]; then
    mkdir -p "${DATA_DIR}"
    printf '; Pre-seeded by scripts/run_tests.sh (macOS data-path fix, workitem #13)\n\n[path]\nread-data=%s\nwrite-data=%s\n\n[general]\nlocale=\n' \
      "${READ_DATA}" "${DATA_DIR}" > "${DATA_DIR}/config.ini"
  fi
fi
# ---------------------------------------------------------------------------

RAW_LOG="$(mktemp)"
trap 'rm -f "${RAW_LOG}"' EXIT

# Run the tests, capturing combined output. The npm package is `factorio-test-cli`
# but its bin is `factorio-test`, so name both explicitly for npx. --config points
# at factorio-test.json (also the default) and -p at the mod (this repo).
npx --yes -p factorio-test-cli factorio-test run -p "${REPO_ROOT}" --config "${REPO_ROOT}/factorio-test.json" 2>&1 | tee "${RAW_LOG}"
STATUS=${PIPESTATUS[0]}

if [ "${STATUS}" -eq 0 ]; then
  RESULT_LINE="✅ PASS — all tests passed."
else
  RESULT_LINE="❌ FAIL — exit code ${STATUS}. See raw output below."
fi

{
  echo "# Quick Mall — Automated Test Results"
  echo
  echo "_Generated by \`scripts/run_tests.sh\` (workitem #13). Refreshed every 6 hours by cron._"
  echo
  echo "- **Runner:** FactorioTest CLI (\`npx factorio-test-cli run\`), headless Factorio"
  echo "- **Spec:** \`tests/qm-blueprint-tests.lua\` (exercises real \`scripts/*\` modules)"
  echo "- **Result:** ${RESULT_LINE}"
  echo
  echo "## Raw run output"
  echo
  echo '```'
  cat "${RAW_LOG}"
  echo '```'
} > "${REPORT}"

echo
echo "Report written to ${REPORT} (exit ${STATUS})."
exit "${STATUS}"
